[package]
name = "graphql_bridge"
version = "0.1.0"
authors = ["Felix Descoteaux <flx.descoteaux@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.4"
apollo-parser = "0.4"
